version: "3"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - webnet

  db:
    image: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data/
    networks:
      - webnet

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    networks:
      - webnet

networks:
  webnet:

volumes:
  dbdata:
