# Generated by Django 4.1.5 on 2023-06-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_rename_created_by_company_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(default='defaultCity', max_length=256),
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.CharField(default='defaultCountry', max_length=256),
        ),
        migrations.AddField(
            model_name='company',
            name='state',
            field=models.CharField(default='defaultState', max_length=256),
        ),
    ]
